[package]

name = "zookeeper"
version = "0.1.3"
authors = ["Nandor Kracser <bonifaido@gmail.com>"]
license = "MIT"
homepage = "https://github.com/bonifaido/rust-zookeeper"
repository = "https://github.com/bonifaido/rust-zookeeper"
documentation = "http://bonifaido.github.io/rust-zookeeper"
description = "A minimal ZooKeeper client, work in progress"
readme = "README.md"
keywords = ["zookeeper", "distributed", "coordination"]

[dependencies]
byteorder = "0.3"
bytes = "0.2"
enum_primitive = "0.1.0"
lazy_static = "0.1"
log = "0.3"
mio = {git = "https://github.com/carllerche/mio.git"}
num = "0.1"

[dev-dependencies]
env_logger = "0.3"
log4rs = "0.3"

[features]
unstable = []
