[package]

name = "zookeeper"
version = "0.0.4"
authors = ["Nandor Kracser <bonifaido@gmail.com>"]
license = "MIT"
homepage = "https://github.com/bonifaido/rust-zookeeper"
repository = "https://github.com/bonifaido/rust-zookeeper"
description = "A minimal ZooKeeper client, work in progress"
readme = "README.md"
